version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard-app
    network_mode: "host"
    ports:
      - "3000:3000"
    volumes:
      # Mount the local directory to /app in the container for live-reloading
      - .:/app
      # Exclude the host's node_modules from overriding the container's node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
